### ISSUE TITLE
App crahs in Android 8.1 setting in Spanish

### ISSUE THREAD

**Issue by Pepepotero** [rnd-ash/MBUX-Port#2]
Hello

I tried to run the app in a tablet with Adroid 8.1 set in Spanish language. The app start but in one second crashed, but when I changed the tablet language to English-Usa or Gb, the app worked.
I think that is something about regional setting (decimal separator, I think), But I am not able to find where the problem is.
Thank for your help.

**Comment by rnd-ash** [comment]
Hmm, Ill try and replicate this later today

**Comment by Pepepotero** [comment]
I forgot to say that I changed the UI text and messages text including a resource file in order to change easily the language.
Attached file is the file strings.xml in Spanish.

I'm working in other strings.xml in english

Sorry but I'm working slowly because I started recently with android studio and Java

[strings.zip](https://github.com/rnd-ash/MBUX-Port/files/5356187/strings.zip)

**Comment by Pepepotero** [comment]
At the end I can caught the error exception installing app in Android 10 phone.
The exception is: 
java.util.UnknownFormatConversionException: Conversion = ' '
	at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2782)
	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2812)
	at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2625)
	at java.util.Formatter.parse(Formatter.java:2558)
	at java.util.Formatter.format(Formatter.java:2505)
	at java.util.Formatter.format(Formatter.java:2459)
	at java.lang.String.format(String.java:2870)
	at com.rndash.mbheadunit.ui.PTDisplay$onViewCreated$1$run$1.run(PTDisplay.kt:51)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(Zygote

**Comment by Pepepotero** [comment]
Oh my god! It's a trifle, a rookie mistake. I forgot to add "d" after %4 in
<string name="ptd_fuel_usage">Uso de Combustible: %4 u/s </string>

Sorry for the inconvenience
